### ISSUE TITLE
Is this still functional? I'm not getting the desired response 

### ISSUE THREAD

**Issue by marvelmaniac** [DreyAnd/WhoDupMe#2]
Tried seeing who duped me in a report to linkedin. The tool takes some time and responds with - "Unfortunately we couldn't find who duped...."
I am positive about providing the necessary details needed by the tool

**Comment by DreyAnd** [comment]
Hi @marvelmaniac thanks for letting me know.

I heard from a couple people as well that they're having issues with it. 
I plan to take a further look into it however I can't gurantee when - hopefully during this weekend.

However make sure the report ID is the ID from the duplicate report, not the original one and also that the duplicated report is actually resolved.

I'll make sure to add more clarification for this as well.

**Comment by marvelmaniac** [comment]
Hey @DreyAnd, no worries. Can you share the api requests that discloses the username of the original reporter ?

**Comment by DreyAnd** [comment]
@marvelmaniac Yeah for sure.

While proxying the program hacktivity page `https://hackerone.com/<program>/hacktivity` you can find the related request.

It's the following GraphQL query at `/graphql` :
```json
{"operationName":"TeamHacktivityPageQuery","variables":{"where":{"team":{"handle":{"_eq":"<program_name>"}}},"handle":"<program_name>","orderBy":{"field":"popular","direction":"DESC"},"secureOrderBy":null,"count":25,"product_area":"other","product_feature":"other"},"query":"query TeamHacktivityPageQuery($handle: String!, $orderBy: HacktivityItemOrderInput, $secureOrderBy: FiltersHacktivityItemFilterOrder, $where: FiltersHacktivityItemFilterInput, $count: Int, $cursor: String) {\n  me {\n    id\n    __typename\n  }\n  team(handle: $handle) {\n    id\n    name\n    __typename\n  }\n  hacktivity_items(\n    first: $count\n    after: $cursor\n    order_by: $orderBy\n    secure_order_by: $secureOrderBy\n    where: $where\n  ) {\n    total_count\n    ...HacktivityList\n    __typename\n  }\n}\n\nfragment HacktivityList on HacktivityItemConnection {\n  pageInfo {\n    endCursor\n    hasNextPage\n    __typename\n  }\n  edges {\n    node {\n      ... on HacktivityItemInterface {\n        id\n        databaseId: _id\n        __typename\n      }\n      __typename\n    }\n    ...HacktivityItem\n    __typename\n  }\n  __typename\n}\n\nfragment HacktivityItem on HacktivityItemUnionEdge {\n  node {\n    ... on HacktivityItemInterface {\n      id\n      type: __typename\n    }\n    ... on Undisclosed {\n      id\n      ...HacktivityItemUndisclosed\n      __typename\n    }\n    ... on Disclosed {\n      id\n      ...HacktivityItemDisclosed\n      __typename\n    }\n    ... on HackerPublished {\n      id\n      ...HacktivityItemHackerPublished\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment HacktivityItemUndisclosed on Undisclosed {\n  id\n  votes {\n    total_count\n    __typename\n  }\n  upvoted: upvoted_by_current_user\n  reporter {\n    id\n    username\n    ...UserLinkWithMiniProfile\n    __typename\n  }\n  team {\n    handle\n    name\n    medium_profile_picture: profile_picture(size: medium)\n    url\n    id\n    ...TeamLinkWithMiniProfile\n    __typename\n  }\n  latest_disclosable_action\n  latest_disclosable_activity_at\n  requires_view_privilege\n  total_awarded_amount\n  currency\n  __typename\n}\n\nfragment TeamLinkWithMiniProfile on Team {\n  id\n  handle\n  name\n  __typename\n}\n\nfragment UserLinkWithMiniProfile on User {\n  id\n  username\n  __typename\n}\n\nfragment HacktivityItemDisclosed on Disclosed {\n  id\n  reporter {\n    id\n    username\n    ...UserLinkWithMiniProfile\n    __typename\n  }\n  votes {\n    total_count\n    __typename\n  }\n  upvoted: upvoted_by_current_user\n  team {\n    handle\n    name\n    medium_profile_picture: profile_picture(size: medium)\n    url\n    id\n    ...TeamLinkWithMiniProfile\n    __typename\n  }\n  report {\n    id\n    databaseId: _id\n    title\n    substate\n    url\n    report_generated_content {\n      id\n      hacktivity_summary\n      __typename\n    }\n    __typename\n  }\n  latest_disclosable_action\n  latest_disclosable_activity_at\n  total_awarded_amount\n  severity_rating\n  currency\n  __typename\n}\n\nfragment HacktivityItemHackerPublished on HackerPublished {\n  id\n  reporter {\n    id\n    username\n    ...UserLinkWithMiniProfile\n    __typename\n  }\n  votes {\n    total_count\n    __typename\n  }\n  upvoted: upvoted_by_current_user\n  team {\n    id\n    handle\n    name\n    medium_profile_picture: profile_picture(size: medium)\n    url\n    ...TeamLinkWithMiniProfile\n    __typename\n  }\n  report {\n    id\n    url\n    title\n    substate\n    __typename\n  }\n  latest_disclosable_activity_at\n  severity_rating\n  __typename\n}\n"}
```

The response will contain multiple `databaseId` properties which are equal to the duped report ID.

For example:
![Image](https://i.imgur.com/XO41N74.png)

The reason why there was a need for a tool to be built is because of pagination, since you can get at maximum 100 reports via `count` parameter and you have to loop through other things to get all the reports (in case the report you're checking is not so recent).
 
What I do notice now is that there are some new parameters required in the API, which is probably why the tool fails.

Will try to fix this as soon as possible :)

**Comment by DreyAnd** [comment]
Hi @marvelmaniac I belive this is fixed in https://github.com/DreyAnd/WhoDupMe/commit/76ee762c2e4236d0801d9765ad1d8d3af6c07d20 

My logic for the pagination was flawed, so makes sense it would only work on specific programs.

About the speed, i added some concurrency which does speed up things a little however, to make significant difference i'd have to rewrite the whole tool to have a different logic yet again since the current workaround loads all the report information inside memory and then checks them all for your report ID - this works but tends to be slow on programs that have *a lot* of reports like LinkedIn in your case. Eventually i'll make all this be done on the fly, in case people care enough.

Current measurement for a report on LinkedIn is around 7 minutes, so make sure to get some popcorn i guess xD?

Anyways, please let me know if the tool works for you now.
